config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'} do
      match "companies/:company_id/sign_up" => "users/registrations#new", as: new_user_company_registration
    end
  end

  root to: 'companies#index'
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  def index
    @company = Company.all
  end
  def new
    @company = Company.new
  end
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @users = User.where(company_id: 4)
  end

  def edit
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @company.destroy
    redirect_to root_path
  end

  private
  def company_params
    params[:company].permit(:name, :chief_user_id)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.slim
=form_for @company do |f|
  =f.text_field :name, placeholder: "法人名"
  =f.submit "法人を追加する", class:"btn"
= link_to "戻る", root_path

app/views/companies/edit.html.slim
h2 会社名を変更する。
== render 'form'

app/views/companies/index.html.slim
h2 法人一覧
- @company.each do |company|
  = company.name
  br
  = link_to "個別ページ", company_path(company.id)
  br
  = link_to "編集する", edit_company_path(company)
  br
  = link_to "削除する", company_path(company), method: :delete, data: { confirm: 'Are you sure?' }
  br
  br
br
= link_to "代表者の設定", new_company_path
br
= link_to "法人追加", new_company_path
br
= link_to "一般ログアウト", destroy_user_company_session_path(current_user.company_id), method: :delete
br
= link_to "管理者ログアウト", destroy_admin_user_session_path, method: :delete

app/views/companies/new.html.slim
h2 法人追加
== render 'form'

app/views/companies/show.html.slim
h2 = @company.name + "のページ"
h3 = "社員一覧"
- @users.each do |user|
  = user.name
br
= link_to "戻る", root_path